/**
 * Mappatura geografica (Latitudine, Longitudine, Città, Regione e Copertura)
 * per emittenti locali, regionali, canali club/cittadini e broadcaster nazionali.
 */

export interface ChannelGeo {
  city: string;
  region: string;
  province?: string;
  country: string;
  latitude: number;
  longitude: number;
  coverage: string;
  isLocal: boolean;
  badge?: string;
}

export const CHANNEL_GEO_MAP: Record<string, ChannelGeo> = {
  // ─── Canali Locali e Regionali (Puglia, Basilicata, Campania, ecc.) ───
  'tele-norba': {
    city: 'Conversano',
    province: 'BA',
    region: 'Puglia',
    country: 'IT',
    latitude: 40.9678,
    longitude: 17.1154,
    coverage: 'Puglia, Basilicata, Molise (Bari, Lecce, Foggia, Taranto, Brindisi, Matera, Potenza)',
    isLocal: true,
    badge: 'Emittente Regionale Puglia',
  },
  'radionorba-tv': {
    city: 'Conversano',
    province: 'BA',
    region: 'Puglia',
    country: 'IT',
    latitude: 40.9678,
    longitude: 17.1154,
    coverage: 'Puglia, Basilicata, Campania, Molise (Bari, Lecce, Foggia, Napoli, Salerno)',
    isLocal: true,
    badge: 'Emittente Regionale Puglia',
  },
  'trm-h24': {
    city: 'Matera',
    province: 'MT',
    region: 'Basilicata',
    country: 'IT',
    latitude: 40.6664,
    longitude: 16.6043,
    coverage: 'Basilicata e Puglia (Matera, Potenza, Bari, Taranto, Lecce)',
    isLocal: true,
    badge: 'Emittente Locale Basilicata e Puglia',
  },
  'san-marino-rtv': {
    city: 'Città di San Marino',
    region: 'San Marino / Emilia-Romagna',
    country: 'SM',
    latitude: 43.9424,
    longitude: 12.4578,
    coverage: 'Repubblica di San Marino, Emilia-Romagna, Marche (Rimini, Pesaro, Bologna)',
    isLocal: true,
    badge: 'Emittente Territoriale e Nazionale SM',
  },
  'rsi-la-1': {
    city: 'Lugano / Comano',
    region: 'Svizzera Italiana (Canton Ticino)',
    country: 'CH',
    latitude: 46.0037,
    longitude: 8.9511,
    coverage: 'Svizzera Italiana (Canton Ticino, Grigioni) e fascia transfrontaliera Lombardia/Piemonte',
    isLocal: true,
    badge: 'Emittente Svizzera Italiana',
  },
  'rsi-la-2': {
    city: 'Lugano / Comano',
    region: 'Svizzera Italiana (Canton Ticino)',
    country: 'CH',
    latitude: 46.0037,
    longitude: 8.9511,
    coverage: 'Svizzera Italiana (Canton Ticino, Grigioni) e fascia transfrontaliera Lombardia/Piemonte',
    isLocal: true,
    badge: 'Emittente Svizzera Italiana',
  },

  // ─── Canali Tematici di Squadra / Città (Serie A / Club) ───
  'seriea-napoli': {
    city: 'Napoli',
    province: 'NA',
    region: 'Campania',
    country: 'IT',
    latitude: 40.8518,
    longitude: 14.2681,
    coverage: 'Napoli, Campania e territorio nazionale',
    isLocal: true,
    badge: 'Canale Club Napoli',
  },
  'seriea-lecce': {
    city: 'Lecce',
    province: 'LE',
    region: 'Puglia',
    country: 'IT',
    latitude: 40.3548,
    longitude: 18.1724,
    coverage: 'Lecce, Salento e territorio nazionale',
    isLocal: true,
    badge: 'Canale Club Lecce',
  },
  'inter-tv': {
    city: 'Milano',
    province: 'MI',
    region: 'Lombardia',
    country: 'IT',
    latitude: 45.4642,
    longitude: 9.1900,
    coverage: 'Milano, Lombardia e territorio nazionale',
    isLocal: true,
    badge: 'Canale Ufficiale FC Internazionale Milano',
  },
  'seriea-inter': {
    city: 'Milano',
    province: 'MI',
    region: 'Lombardia',
    country: 'IT',
    latitude: 45.4642,
    longitude: 9.1900,
    coverage: 'Milano, Lombardia e territorio nazionale',
    isLocal: true,
    badge: 'Canale Club Inter',
  },
  'milan-tv': {
    city: 'Milano',
    province: 'MI',
    region: 'Lombardia',
    country: 'IT',
    latitude: 45.4642,
    longitude: 9.1900,
    coverage: 'Milano, Lombardia e territorio nazionale',
    isLocal: true,
    badge: 'Canale Ufficiale AC Milan',
  },
  'seriea-milan': {
    city: 'Milano',
    province: 'MI',
    region: 'Lombardia',
    country: 'IT',
    latitude: 45.4642,
    longitude: 9.1900,
    coverage: 'Milano, Lombardia e territorio nazionale',
    isLocal: true,
    badge: 'Canale Club Milan',
  },
  'seriea-roma': {
    city: 'Roma',
    province: 'RM',
    region: 'Lazio',
    country: 'IT',
    latitude: 41.9028,
    longitude: 12.4964,
    coverage: 'Roma, Lazio e territorio nazionale',
    isLocal: true,
    badge: 'Canale Club AS Roma',
  },
  'seriea-lazio': {
    city: 'Roma',
    province: 'RM',
    region: 'Lazio',
    country: 'IT',
    latitude: 41.9028,
    longitude: 12.4964,
    coverage: 'Roma, Lazio e territorio nazionale',
    isLocal: true,
    badge: 'Canale Club SS Lazio',
  },
  'seriea-juventus': {
    city: 'Torino',
    province: 'TO',
    region: 'Piemonte',
    country: 'IT',
    latitude: 45.0703,
    longitude: 7.6869,
    coverage: 'Torino, Piemonte e territorio nazionale',
    isLocal: true,
    badge: 'Canale Club Juventus',
  },
  'seriea-torino': {
    city: 'Torino',
    province: 'TO',
    region: 'Piemonte',
    country: 'IT',
    latitude: 45.0703,
    longitude: 7.6869,
    coverage: 'Torino, Piemonte e territorio nazionale',
    isLocal: true,
    badge: 'Canale Club Torino FC',
  },
  'seriea-fiorentina': {
    city: 'Firenze',
    province: 'FI',
    region: 'Toscana',
    country: 'IT',
    latitude: 43.7696,
    longitude: 11.2558,
    coverage: 'Firenze, Toscana e territorio nazionale',
    isLocal: true,
    badge: 'Canale Club ACF Fiorentina',
  },
  'seriea-bologna': {
    city: 'Bologna',
    province: 'BO',
    region: 'Emilia-Romagna',
    country: 'IT',
    latitude: 44.4949,
    longitude: 11.3426,
    coverage: 'Bologna, Emilia-Romagna e territorio nazionale',
    isLocal: true,
    badge: 'Canale Club Bologna FC',
  },
  'seriea-atalanta': {
    city: 'Bergamo',
    province: 'BG',
    region: 'Lombardia',
    country: 'IT',
    latitude: 45.6983,
    longitude: 9.6773,
    coverage: 'Bergamo, Lombardia e territorio nazionale',
    isLocal: true,
    badge: 'Canale Club Atalanta BC',
  },
  'seriea-cagliari': {
    city: 'Cagliari',
    province: 'CA',
    region: 'Sardegna',
    country: 'IT',
    latitude: 39.2238,
    longitude: 9.1217,
    coverage: 'Cagliari, Sardegna e territorio nazionale',
    isLocal: true,
    badge: 'Canale Club Cagliari Calcio',
  },
  'seriea-como': {
    city: 'Como',
    province: 'CO',
    region: 'Lombardia',
    country: 'IT',
    latitude: 45.8081,
    longitude: 9.0852,
    coverage: 'Como, Lombardia e territorio nazionale',
    isLocal: true,
    badge: 'Canale Club Como 1907',
  },
  'seriea-cremonese': {
    city: 'Cremona',
    province: 'CR',
    region: 'Lombardia',
    country: 'IT',
    latitude: 45.1332,
    longitude: 10.0247,
    coverage: 'Cremona, Lombardia e territorio nazionale',
    isLocal: true,
    badge: 'Canale Club US Cremonese',
  },
  'seriea-genoa': {
    city: 'Genova',
    province: 'GE',
    region: 'Liguria',
    country: 'IT',
    latitude: 44.4056,
    longitude: 8.9463,
    coverage: 'Genova, Liguria e territorio nazionale',
    isLocal: true,
    badge: 'Canale Club Genoa CFC',
  },
  'seriea-hellas-verona': {
    city: 'Verona',
    province: 'VR',
    region: 'Veneto',
    country: 'IT',
    latitude: 45.4384,
    longitude: 10.9916,
    coverage: 'Verona, Veneto e territorio nazionale',
    isLocal: true,
    badge: 'Canale Club Hellas Verona',
  },
  'seriea-parma': {
    city: 'Parma',
    province: 'PR',
    region: 'Emilia-Romagna',
    country: 'IT',
    latitude: 44.8015,
    longitude: 10.3279,
    coverage: 'Parma, Emilia-Romagna e territorio nazionale',
    isLocal: true,
    badge: 'Canale Club Parma Calcio',
  },
  'seriea-pisa': {
    city: 'Pisa',
    province: 'PI',
    region: 'Toscana',
    country: 'IT',
    latitude: 43.7228,
    longitude: 10.4017,
    coverage: 'Pisa, Toscana e territorio nazionale',
    isLocal: true,
    badge: 'Canale Club Pisa SC',
  },
  'seriea-sassuolo': {
    city: 'Sassuolo',
    province: 'MO',
    region: 'Emilia-Romagna',
    country: 'IT',
    latitude: 44.5407,
    longitude: 10.7831,
    coverage: 'Sassuolo, Modena, Emilia-Romagna e territorio nazionale',
    isLocal: true,
    badge: 'Canale Club US Sassuolo',
  },
  'seriea-udinese': {
    city: 'Udine',
    province: 'UD',
    region: 'Friuli-Venezia Giulia',
    country: 'IT',
    latitude: 46.0626,
    longitude: 13.2305,
    coverage: 'Udine, Friuli-Venezia Giulia e territorio nazionale',
    isLocal: true,
    badge: 'Canale Club Udinese Calcio',
  },

  // ─── Principali Sedi di Produzione ed Emittenti Nazionali ───
  'rai-1': {
    city: 'Roma',
    province: 'RM',
    region: 'Lazio',
    country: 'IT',
    latitude: 41.9172,
    longitude: 12.4633,
    coverage: 'Nazionale (Sede centrale Roma, Centri produzione Milano, Napoli, Torino)',
    isLocal: false,
  },
  'rai-2': {
    city: 'Roma',
    province: 'RM',
    region: 'Lazio',
    country: 'IT',
    latitude: 41.9172,
    longitude: 12.4633,
    coverage: 'Nazionale (Sede centrale Roma, Centri produzione Milano, Napoli, Torino)',
    isLocal: false,
  },
  'rai-3': {
    city: 'Roma',
    province: 'RM',
    region: 'Lazio',
    country: 'IT',
    latitude: 41.9172,
    longitude: 12.4633,
    coverage: 'Nazionale e Regionale TGR (Sedi regionali in tutti i capoluoghi italiani)',
    isLocal: false,
    badge: 'Rete Nazionale con Redazioni Regionali TGR',
  },
  'canale-5': {
    city: 'Cologno Monzese (Milano)',
    province: 'MI',
    region: 'Lombardia',
    country: 'IT',
    latitude: 45.5289,
    longitude: 9.2783,
    coverage: 'Nazionale (Centro di produzione Cologno Monzese, Segrate, Roma)',
    isLocal: false,
  },
  'italia-1': {
    city: 'Cologno Monzese (Milano)',
    province: 'MI',
    region: 'Lombardia',
    country: 'IT',
    latitude: 45.5289,
    longitude: 9.2783,
    coverage: 'Nazionale (Centro di produzione Cologno Monzese, Segrate, Roma)',
    isLocal: false,
  },
  'rete-4': {
    city: 'Cologno Monzese (Milano)',
    province: 'MI',
    region: 'Lombardia',
    country: 'IT',
    latitude: 45.5289,
    longitude: 9.2783,
    coverage: 'Nazionale (Centro di produzione Cologno Monzese e Roma Palatino)',
    isLocal: false,
  },
  'la7': {
    city: 'Roma',
    province: 'RM',
    region: 'Lazio',
    country: 'IT',
    latitude: 41.9133,
    longitude: 12.4933,
    coverage: 'Nazionale (Sede centrale Roma, Studi Milano)',
    isLocal: false,
  },
  'la7d': {
    city: 'Roma',
    province: 'RM',
    region: 'Lazio',
    country: 'IT',
    latitude: 41.9133,
    longitude: 12.4933,
    coverage: 'Nazionale (Sede centrale Roma)',
    isLocal: false,
  },
  'tv8': {
    city: 'Milano Santa Giulia',
    province: 'MI',
    region: 'Lombardia',
    country: 'IT',
    latitude: 45.4369,
    longitude: 9.2394,
    coverage: 'Nazionale (Studi Sky Italia Milano Santa Giulia e Roma)',
    isLocal: false,
  },
  'nove': {
    city: 'Milano',
    province: 'MI',
    region: 'Lombardia',
    country: 'IT',
    latitude: 45.4497,
    longitude: 9.2458,
    coverage: 'Nazionale (Sede Warner Bros. Discovery Milano e Roma)',
    isLocal: false,
  },
  'sky-tg24': {
    city: 'Milano Santa Giulia',
    province: 'MI',
    region: 'Lombardia',
    country: 'IT',
    latitude: 45.4369,
    longitude: 9.2394,
    coverage: 'Nazionale (Sede centrale Milano Santa Giulia, Redazioni Roma, Bruxelles, New York)',
    isLocal: false,
  },
  'sport-italia': {
    city: 'Milano',
    province: 'MI',
    region: 'Lombardia',
    country: 'IT',
    latitude: 45.4642,
    longitude: 9.1900,
    coverage: 'Nazionale (Studi Milano)',
    isLocal: false,
  },
  'supertennis': {
    city: 'Roma',
    province: 'RM',
    region: 'Lazio',
    country: 'IT',
    latitude: 41.9028,
    longitude: 12.4964,
    coverage: 'Nazionale (Sede FITP Roma)',
    isLocal: false,
  },
  'tv2000': {
    city: 'Roma',
    province: 'RM',
    region: 'Lazio',
    country: 'IT',
    latitude: 41.8988,
    longitude: 12.4285,
    coverage: 'Nazionale (Sede Roma Via Aurelia)',
    isLocal: false,
  },
  'rtl-1025': {
    city: 'Cologno Monzese (Milano)',
    province: 'MI',
    region: 'Lombardia',
    country: 'IT',
    latitude: 45.5262,
    longitude: 9.2754,
    coverage: 'Nazionale (Studi Cologno Monzese, Roma e Napoli)',
    isLocal: false,
  },
  'deejay-tv': {
    city: 'Milano',
    province: 'MI',
    region: 'Lombardia',
    country: 'IT',
    latitude: 45.4746,
    longitude: 9.1681,
    coverage: 'Nazionale (Studi Radio Deejay Milano Via Massena e Roma)',
    isLocal: false,
  },
  'radio-105': {
    city: 'Milano',
    province: 'MI',
    region: 'Lombardia',
    country: 'IT',
    latitude: 45.4729,
    longitude: 9.1969,
    coverage: 'Nazionale (Studi Milano Largo Donegani e Roma)',
    isLocal: false,
  },
  'r101': {
    city: 'Milano',
    province: 'MI',
    region: 'Lombardia',
    country: 'IT',
    latitude: 45.4729,
    longitude: 9.1969,
    coverage: 'Nazionale (Studi Milano Largo Donegani e Roma)',
    isLocal: false,
  },
};

/** Restituisce i dati geografici e coordinate del canale, se censiti. */
export function getChannelGeo(channelId: string): ChannelGeo | null {
  const id = channelId?.toLowerCase().trim();
  return CHANNEL_GEO_MAP[id] ?? null;
}

/** Restituisce l'elenco di tutte le emittenti locali e regionali enucleate */
export function getLocalChannels(): Array<{ id: string; geo: ChannelGeo }> {
  return Object.entries(CHANNEL_GEO_MAP)
    .filter(([, geo]) => geo.isLocal)
    .map(([id, geo]) => ({ id, geo }));
}
